/* ═══════════════════════════════════════════════════════════
   LEVEL LOADING
   Fetches the pre-made level manifest (/level/N.json), loads a campaign level
   by index, and loads the built-in demo level. Builds via buildLevel3D (main).
   ═══════════════════════════════════════════════════════════ */
import { S } from './state.js';
import { MAX_LIVES } from './constants.js';
import { DEMO_LEVEL } from './levels-data.js';
import { deserializeLevel } from './level.js';
import { buildLevel3D } from './main.js';
import { drawEditorWires } from './editor.js';
import { showMessage } from './ui.js';

export function loadDemoLevel() {
  S.isCustomLevel = true;
  S.playerLives = MAX_LIVES;
  S.activeLevel = deserializeLevel(JSON.stringify(DEMO_LEVEL));
  document.getElementById('level-name-input').value = S.activeLevel.name;
  document.getElementById('world-select').value = S.activeLevel.world;
  buildLevel3D(S.activeLevel);
  if (S.isEditMode && !S.isPlaytesting) drawEditorWires();
  showMessage('DEMO LEVEL LOADED');
}



/* ═══════════════════════════════════════════════════════════
   PRE-MADE LEVEL LOADER
   ═══════════════════════════════════════════════════════════ */
// Load level list from manifest.json (generated by `npm run generate-manifest`).
// Every .json file in /level/ except manifest.json itself is included.
export async function loadLevelManifest() {
  const levels = [];
  let files = [];
  try {
    const res = await fetch('level/manifest.json', { cache: 'no-cache' });
    if (res.ok) {
      const m = await res.json();
      if (Array.isArray(m)) files = m.map(f => (typeof f === 'string' ? f : f.file)).filter(Boolean);
    }
  } catch (e) { /* no manifest */ }
  if (!files.length) {
    console.warn('[loadLevelManifest] No manifest.json found – no campaign levels loaded.');
    return levels;
  }
  for (const file of files) {
    let res;
    try { res = await fetch(`level/${file}`, { cache: 'no-cache' }); }
    catch (e) { continue; }
    if (!res.ok) continue;
    let text;
    try { text = await res.text(); } catch (e) { continue; }
    let data;
    try { data = JSON.parse(text); } catch (e) { continue; }
    if (!data || !Array.isArray(data.blocks) || !data.start || !data.exit) continue;
    levels.push(text);
  }
  return levels;
}

export function loadPreMadeLevel(idx) {
  S.isCustomLevel = false;
  S.playerLives = MAX_LIVES;
  if (!S.premadeLevels.length) return; // manifest not ready (or no level files)
  const n = S.premadeLevels.length;
  const i = ((idx % n) + n) % n;
  const lvl3D = deserializeLevel(S.premadeLevels[i]);
  buildLevel3D(lvl3D);
}

